spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    consumer:
      group-id: order-consumer
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.common.model.Order
        spring.json.trusted.packages: com.example.common.model
        spring.json.value.type.method: DEFAULT_TYPE

    admin:
      auto-create: true

server:
  port: ${SERVER_PORT:8083}
